clc
close all
clear all
path_mat = './KP_Experiment/'
addpath(path_mat)
addpath('/home/a.brugnoli/GitProjects/MatlabProjects/PH/Functions/')
renameFiles(path_mat)


load M; load J; load R; load B; load C; 
load Mr; load Jr; load Rr; load Br; load Cr;
sys_full = dss(J-R,B,C,[0, 0],M);
sys_red = dss(Jr-Rr,Br,Cr,[0, 0],Mr);

% sys_full = minreal(sys_full);
% sys_red = minreal(sys_red);

fntsize = 15;
figure()

sigma(sys_red(1, 1)*tf(1, [1 0]), '-*r', sys_full(1, 1)*tf(1, [1 0]), '-b', {5*2*pi, 150*2*pi})
% set_graphics_sigma(gca, fntsize)
set(gca,...
'Units','normalized',...
'FontWeight','normal',...
'FontUnits','points',...
'FontSize',fntsize,...
'FontName','Times')
ylabel('$\sigma$',...
'FontUnits','points',...
'interpreter', 'latex',...
'FontSize',fntsize,...
'FontName','Times')
xlabel('Frequency',...
'FontUnits','points',...
'interpreter', 'latex',...
'FontWeight','normal',...
'FontSize',fntsize,...
'FontName','Times')
legend({'KP red', 'KP full'},...
'FontSize',fntsize,...
'interpreter', 'latex',...
'FontName','Times',...
'Location','NorthEast')

