% Axis for singular values set
function set_graphics(current_axis, x_label, y_label, varargin)
% only want n_opt optional inputs at most
n_opt = 3;
numvarargs = length(varargin);
if numvarargs > n_opt
    error(strcat('myfuns:somefun2Alt:TooManyInputs', ...
        'requires at most', int2str(n_opt) , 'optional inputs'));
end

% set defaults for optional inputs
optargs = {'', 13, ''};

% now put these defaults into the valuesToUse cell array, 
% and overwrite the ones specified in varargin.
optargs(1:numvarargs) = varargin;
% or ...
% [optargs{1:numvarargs}] = varargin{:};

% Place optional args in memorable variable names
[leg, fntsize, titl] = optargs{:};

set(current_axis,...
'Units','normalized',...
'FontWeight','normal',...
'FontUnits','points',...
'FontSize',fntsize,...
'FontName','Times')
ylabel(y_label,...
'FontUnits','points',...
'interpreter', 'latex',...
'FontSize',fntsize,...
'FontName','Times')
xlabel(x_label,...
'FontUnits','points',...
'interpreter', 'latex',...
'FontWeight','normal',...
'FontSize',fntsize,...
'FontName','Times')
legend(leg,...
'FontSize',fntsize,...
'interpreter', 'latex',...
'FontName','Times',...
'Location','NorthEast')
title(titl, ...
'FontUnits','points',...
'interpreter', 'latex',...
'FontWeight','normal',...
'FontSize',fntsize,...
'FontName','Times')

end