% Axis for singular values set
function set_graphics_sigma(current_axis, varargin)
% only want n_opt optional inputs at most
n_opt = 1;
numvarargs = length(varargin);
if numvarargs > n_opt
    error(strcat('myfuns:somefun2Alt:TooManyInputs', ...
        'requires at most', int2str(n_opt) , 'optional inputs'));
end

% set defaults for optional inputs
optargs = {13};

% now put these defaults into the valuesToUse cell array, 
% and overwrite the ones specified in varargin.
optargs(1:numvarargs) = varargin;
% or ...
% [optargs{1:numvarargs}] = varargin{:};

% Place optional args in memorable variable names
[fntsize] = optargs{:};

set(current_axis,...
'Units','normalized',...
'FontWeight','normal',...
'FontUnits','points',...
'FontSize',fntsize,...
'FontName','Times')
ylabel('$\sigma(\omega)$',...
'FontUnits','points',...
'FontSize',fntsize,...
'interpreter', 'latex',...
'FontName','Times')
xlabel('Frequency',...
'FontUnits','points',...
'FontWeight','normal',...
'interpreter', 'latex',...
'FontSize',fntsize,...
'FontName','Times')
legend('FontSize',fntsize,...
'FontName','Times',...
'interpreter', 'latex',...
'Location','NorthEast')
title('Singular Values',...
'FontUnits','points',...
'FontWeight','normal',...
'interpreter', 'latex',...
'FontSize',fntsize,...
'FontName','Times')

end